addSbtPlugin("com.typesafe"   % "sbt-mima-plugin"    % "1.1.6")
addSbtPlugin("com.github.sbt" % "sbt-java-formatter" % "0.12.0")
addSbtPlugin("com.github.sbt" % "sbt-header"         % "5.11.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"       % "2.6.1")
addSbtPlugin("com.github.sbt" % "sbt-ci-release"     % "1.11.2")
