addSbtPlugin("com.typesafe"      % "sbt-mima-plugin"    % "1.1.4")
addSbtPlugin("com.lightbend.sbt" % "sbt-java-formatter" % "0.8.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"         % "5.10.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"       % "2.5.4")
addSbtPlugin("com.github.sbt"    % "sbt-ci-release"     % "1.9.3")
